### PR TITLE
Update and improve Italian translation

### PR DESCRIPTION
**Pull request by Fs00**
I took the time to make some miscellaneous fixes and wording improvements to the already good Italian translation.
I have also updated translations that were outdated and added some missing ones.

### CODE REVIEW

**Comment by Pdevo** [comment]
Well done, the quality is superb and everything is self-explanatory

**Comment by Fs00** [comment]
@mar-v-in Is there anything that keeps this on hold? Do you have any doubts about the translations?

**Comment by ale5000-git** [comment]
I think he is just busy.

**Comment by mar-v-in** [comment]
Thanks for providing the translations.

**Comment by Fs00** [comment]
You're welcome!

**Pull request merged**
