### PR TITLE
SettingsProvider: Remove logs

### PR DESCRIPTION
**Pull request by chirayudesai**
* This is really spammy!

Change-Id: If1b9cbaa50bf8af37ca7146c6f510ad6875bab35

### CODE REVIEW

**Comment by chirayudesai** [comment]
Cc: @grote

**Comment by grote** [comment]
yeah, if everything works as expected they can be removed, but their spammyness might also hint at some bugs that access settings too frequently.

**Comment by RobertoWa** [comment]
what about a on/off switch for logging?

**Comment by mar-v-in** [comment]
Thanks.

**Pull request merged**
