### PR TITLE
Provisioning: Location providers

### PR DESCRIPTION
**Pull request by t-m-w**
New provisioning extras to control Location features:
* Internet lookups (Mozilla Location Services): wifi_mls, cell_mls
* Local location learning: wifi_learning, cell_learning
* Query location from supported hotspots: wifi_moving
* Geocoder (Nominatim): nominatim_enabled

### CODE REVIEW

**Comment by mar-v-in** [comment]
This looks reasonable. Note though that (starting next version) all providers will be disabled by default (except when the corresponding UnifiedNlp module was enabled before the upgrade - having them enabled by default was actually by accident), so this will be more useful as an opt-in ;)

**Comment by t-m-w** [comment]
> This looks reasonable. Note though that (starting next version) all providers will be disabled by default (except when the corresponding UnifiedNlp module was enabled before the upgrade - having them enabled by default was actually by accident), so this will be more useful as an opt-in ;)

Good to know, and thanks for checking this out so quickly. I was asked to make it more granular, so I just did that now.

**Comment by t-m-w** [comment]
I see again what you mean about location settings being off by default, including location learning! So I added a few more settings to this, since I think users will commonly want location learning enabled.

**Comment by mar-v-in** [comment]
In case anyone wonders why location learning is disabled by default: it effectively creates a local database of locations where the smartphone used GPS over the last weeks. For some people that may be problematic, so that's why it makes sense to be opt-in, so they're not surprised by that.

**Pull request merged**
