### PR TITLE
Add getConfiguration for LocationSettingsRequest

### PR DESCRIPTION
**Pull request by dylangerdaly**
Fixes `Unknown field num 3 in com.google.android.gms.location.LocationSettingsRequest, skipping.` error

This was super  quick and dirty, I didn't test too much

### CODE REVIEW

**Comment by mar-v-in** [comment]
`getConfiguration` is not of type integer, so this hides the warning message but doesn't give a useful result either.

**Comment by dylangerdaly** [comment]
I know, I don't know how to recreate the correct type though, this fixes Tinder anyway

Try re-create the actual object

-------- Original Message --------

**Comment by mar-v-in** [comment]
I added the correct object and pushed in commit 6555997664b83ccc7aa20edaa9ea780a5da2ed8a. Thanks for looking into this.

**Comment by dylangerdaly** [comment]
Thank you for making the correct object,

Sorry my last message was supposed to say "I'll try add" not "Try add", sorry if that came across rude

-------- Original Message --------

**Pull request closed without merging**
