### PR TITLE
Fix crashes of the interface in legacy Android versions

### PR DESCRIPTION
**Pull request by ale5000-git**
Although it isn't a real fix it give a working and reasonably similar graphical interface on legacy Androids.
No change on new Androids.

**Edit:** Now xml files are fixed.

On KitKat:
settings-on-kitkat

### CODE REVIEW

**Comment by mar-v-in** [comment]
What's the exception you are seeing? Is that on specific SDK levels and can we bind this behavior to SDK level instead?

**Comment by ale5000-git** [comment]
SDK 19 (KitKat) => Crash
SDK 21 (Lollipop) => Crash
SDK 25 (Nougat) => OK

SDK 22 is still Lollipop so maybe it is the same
SDK 24 is still Nougat so maybe it is the same

The only one unknown is SDK 23 (Marshmallow).

**Comment by ale5000-git** [comment]
KitKat crash:
```
E/AndroidRuntime( 1433): FATAL EXCEPTION: main
E/AndroidRuntime( 1433): Process: com.google.android.gms:ui, PID: 1433
E/AndroidRuntime( 1433): android.view.InflateException: Binary XML file line #14: Error inflating class org.microg.gms.ui.SwitchBarPreference
E/AndroidRuntime( 1433): 	at androidx.preference.PreferenceInflater.createItem(PreferenceInflater.java:253)
E/AndroidRuntime( 1433): 	at androidx.preference.PreferenceInflater.createItemFromTag(PreferenceInflater.java:281)
E/AndroidRuntime( 1433): 	at androidx.preference.PreferenceInflater.rInflate(PreferenceInflater.java:349)
E/AndroidRuntime( 1433): 	at androidx.preference.PreferenceInflater.inflate(PreferenceInflater.java:161)
E/AndroidRuntime( 1433): 	at androidx.preference.PreferenceInflater.inflate(PreferenceInflater.java:112)
E/AndroidRuntime( 1433): 	at androidx.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:217)
E/AndroidRuntime( 1433): 	at androidx.preference.PreferenceFragmentCompat.addPreferencesFromResource(PreferenceFragmentCompat.java:364)
E/AndroidRuntime( 1433): 	at org.microg.gms.ui.DeviceRegistrationFragment.onCreatePreferences(DeviceRegistrationFragment.kt:70)
E/AndroidRuntime( 1433): 	at androidx.preference.PreferenceFragmentCompat.onCreate(PreferenceFragmentCompat.java:161)
E/AndroidRuntime( 1433): 	at org.microg.gms.ui.DeviceRegistrationFragment.onCreate(DeviceRegistrationFragment.kt:46)
E/AndroidRuntime( 1433): 	at androidx.fragment.app.Fragment.performCreate(Fragment.java:3094)
E/AndroidRuntime( 1433): 	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:504)
E/AndroidRuntime( 1433): 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:268)
E/AndroidRuntime( 1433): 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1943)
E/AndroidRuntime( 1433): 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1845)
E/AndroidRuntime( 1433): 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1782)
E/AndroidRuntime( 1433): 	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:565)
E/AndroidRuntime( 1433): 	at android.os.Handler.handleCallback(Handler.java:733)
E/AndroidRuntime( 1433): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime( 1433): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 1433): 	at android.app.ActivityThread.main(ActivityThread.java:5001)
E/AndroidRuntime( 1433): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 1433): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 1433): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
E/AndroidRuntime( 1433): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
E/AndroidRuntime( 1433): 	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 1433): Caused by: java.lang.reflect.InvocationTargetException
E/AndroidRuntime( 1433): 	at java.lang.reflect.Constructor.constructNative(Native Method)
E/AndroidRuntime( 1433): 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
E/AndroidRuntime( 1433): 	at androidx.preference.PreferenceInflater.createItem(PreferenceInflater.java:246)
E/AndroidRuntime( 1433): 	... 25 more
E/AndroidRuntime( 1433): Caused by: android.content.res.Resources$NotFoundException: File res/c4.xml from drawable resource ID #0x7f0801bc
E/AndroidRuntime( 1433): 	at android.content.res.Resources.loadDrawable(Resources.java:2096)
E/AndroidRuntime( 1433): 	at android.content.res.TypedArray.getDrawable(TypedArray.java:602)
E/AndroidRuntime( 1433): 	at org.microg.gms.ui.SwitchBarPreference.<init>(SwitchBarPreference.kt:27)
E/AndroidRuntime( 1433): 	at org.microg.gms.ui.SwitchBarPreference.<init>(SwitchBarPreference.kt:31)
E/AndroidRuntime( 1433): 	at org.microg.gms.ui.SwitchBarPreference.<init>(SwitchBarPreference.kt:32)
E/AndroidRuntime( 1433): 	... 28 more
E/AndroidRuntime( 1433): Caused by: java.lang.UnsupportedOperationException: Can't convert to color: type=0x2
E/AndroidRuntime( 1433): 	at android.content.res.TypedArray.getColor(TypedArray.java:327)
E/AndroidRuntime( 1433): 	at android.graphics.drawable.GradientDrawable.inflate(GradientDrawable.java:970)
E/AndroidRuntime( 1433): 	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:937)
E/AndroidRuntime( 1433): 	at android.graphics.drawable.Drawable.createFromXml(Drawable.java:877)
E/AndroidRuntime( 1433): 	at android.content.res.Resources.loadDrawable(Resources.java:2092)
E/AndroidRuntime( 1433): 	... 32 more
W/ActivityManager(  484):   Force finishing activity com.google.android.gms/org.microg.gms.ui.SettingsActivity
```

**Comment by ale5000-git** [comment]
Lollipop crash:
```
E/AndroidRuntime( 3941): FATAL EXCEPTION: main
E/AndroidRuntime( 3941): Process: com.google.android.gms:ui, PID: 3941
E/AndroidRuntime( 3941): android.view.InflateException: Binary XML file line #46: Error inflating class TextView
E/AndroidRuntime( 3941): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:763)
E/AndroidRuntime( 3941): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
E/AndroidRuntime( 3941): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
E/AndroidRuntime( 3941): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
E/AndroidRuntime( 3941): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
E/AndroidRuntime( 3941): 	at androidx.preference.PreferenceGroupAdapter.onCreateViewHolder(PreferenceGroupAdapter.java:401)
E/AndroidRuntime( 3941): 	at androidx.preference.PreferenceGroupAdapter.onCreateViewHolder(PreferenceGroupAdapter.java:49)
E/AndroidRuntime( 3941): 	at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:7078)
E/AndroidRuntime( 3941): 	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6235)
E/AndroidRuntime( 3941): 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
E/AndroidRuntime( 3941): 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
E/AndroidRuntime( 3941): 	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
E/AndroidRuntime( 3941): 	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1627)
E/AndroidRuntime( 3941): 	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
E/AndroidRuntime( 3941): 	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
E/AndroidRuntime( 3941): 	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
E/AndroidRuntime( 3941): 	at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:3540)
E/AndroidRuntime( 3941): 	at android.view.View.measure(View.java:17430)
E/AndroidRuntime( 3941): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5463)
E/AndroidRuntime( 3941): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
E/AndroidRuntime( 3941): 	at android.view.View.measure(View.java:17430)
E/AndroidRuntime( 3941): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5463)
E/AndroidRuntime( 3941): 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
E/AndroidRuntime( 3941): 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
E/AndroidRuntime( 3941): 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
E/AndroidRuntime( 3941): 	at android.view.View.measure(View.java:17430)
E/AndroidRuntime( 3941): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5463)
E/AndroidRuntime( 3941): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
E/AndroidRuntime( 3941): 	at android.view.View.measure(View.java:17430)
E/AndroidRuntime( 3941): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5463)
E/AndroidRuntime( 3941): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
E/AndroidRuntime( 3941): 	at android.view.View.measure(View.java:17430)
E/AndroidRuntime( 3941): 	at androidx.core.widget.NestedScrollView.measureChildWithMargins(NestedScrollView.java:1921)
E/AndroidRuntime( 3941): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
E/AndroidRuntime( 3941): 	at androidx.core.widget.NestedScrollView.onMeasure(NestedScrollView.java:640)
E/AndroidRuntime( 3941): 	at android.view.View.measure(View.java:17430)
E/AndroidRuntime( 3941): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5463)
E/AndroidRuntime( 3941): 	at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:760)
E/AndroidRuntime( 3941): 	at com.google.android.material.appbar.HeaderScrollingViewBehavior.onMeasureChild(HeaderScrollingViewBehavior.java:100)
E/AndroidRuntime( 3941): 	at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onMeasureChild(AppBarLayout.java:2381)
E/AndroidRuntime( 3941): 	at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:831)
E/AndroidRuntime( 3941): 	at android.view.View.measure(View.java:17430)
E/AndroidRuntime( 3941): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5463)
E/AndroidRuntime( 3941): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
E/AndroidRuntime( 3941): 	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:145)
E/AndroidRuntime( 3941): 	at android.view.View.measure(View.java:17430)
E/AndroidRuntime( 3941): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5463)
E/AndroidRuntime( 3941): 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
E/AndroidRuntime( 3941): 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
E/AndroidRuntime( 3941): 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
E/AndroidRuntime( 3941): 	at android.view.View.measure(View.java:17430)
E/AndroidRuntime( 3941): 	at android.view.ViewGroup.measureChildWit
```

**Comment by ale5000-git** [comment]
@mar-v-in
For now I have excluded Marshmallow from the fix because I don't know, everything else should be OK.

**Comment by mar-v-in** [comment]
Can you try if the following changes in `play-services-core` works for you on legacy systems instead of your code:
- Move [`Theme.Base.Preference.SwitchBarPreference`](https://github.com/microg/GmsCore/blob/master/play-services-core/src/main/res/values/themes.xml#L41-L47) to `values-v23/themes.xml`
- Copy [`Theme.Base.PreferenceThemeOverlay`](https://github.com/microg/GmsCore/blob/master/play-services-core/src/main/res/values/themes.xml#L32-L35) to `values-v23/themes.xml`
- Remove [`switchBarPreferenceStyle`](https://github.com/microg/GmsCore/blob/master/play-services-core/src/main/res/values/themes.xml#L34) from the `Theme.Base.PreferenceThemeOverlay` in `values/themes.xml`
- Move `drawable-v21/material_switch_bar_background.xml` and `drawable-v21/material_switch_bar_background.xml` to `drawable-v23`
- Remove `drawable/material_switch_bar_background.xml` and `drawable/material_switch_bar_background.xml`

This should effectively lead to the same result (falling back to the non-material style SwitchBar) on pre-23 systems, but makes it more explicit in the theme that those are not used.

**Comment by ale5000-git** [comment]
@mar-v-in
Updated.
It now works, thanks

**Review by mar-v-in — APPROVED** [review]

**Pull request merged**
