### PR TITLE
Fix the icon of microG settings inside Android settings on Android < 8, fix #2057

### LINKED ISSUE #2057: microG settings icon inside Android settings is missing on Nougat
The icon of `microG Settings embedded in System Settings on SDK 23` is missing on Nougat.

Screenshot_20230922-180320

---

In the past it was like this:
microg-settings

### PR DESCRIPTION
**Pull request by ale5000-git**
Fix the icon of microG settings inside Android settings on Android < 8, fix #2057

This is probably something left out from this commit: https://github.com/microg/GmsCore/commit/90f8a6a50243d9fd84d1b11ee9c54e830c4e227f

### CODE REVIEW

**Comment by Wojtaz0w** [comment]
does it fix issue created by me? #2059

**Comment by ale5000-git** [comment]
Obviously no.
In the title there is "Android < 8" that mean "Android version less than 8", in this case in particular apply to:
```
Android 7.x
Android 6.x
```

**Comment by Wojtaz0w** [comment]
Nevermind, i didnt read that part of title... sorry

**Comment by ale5000-git** [comment]
Don't worry, on newer Android it use a different file so they are completely separate.

**Comment by ale5000-git** [comment]
@mar-v-in
I have also tried to reuse the drawable from here on Nougat: https://github.com/microg/GmsCore/blob/master/play-services-core/src/main/res/drawable-v26/ic_app_settings_foreground_mono.xml

It generally works but it is too small and if I try to resize it it get disaligned and truncated.
Since the benefit of vectorial images is to render correctly at any size I conclude that the xml is broken.

**Comment by mar-v-in** [comment]
I added the missing icon via 44b9173476c4f293649507703e9179d24667754d

Not sure what issue you had with the vector drawable, but resizing it worked fine for me.

**Comment by ale5000-git** [comment]
@mar-v-in

With your changes it works.

Is this file still needed? https://github.com/microg/GmsCore/blob/master/play-services-core/src/main/res/drawable-anydpi-v21/microg_light_color_24.xml

**Pull request closed without merging**
