### PR TITLE
Translation permission related (Chinese (Simplified))

### PR DESCRIPTION
**Pull request by DaVinci9196**

### CODE REVIEW

**Comment by ygorigor** [comment]
Translations are now on weblate https://hosted.weblate.org/projects/microg/play-services-location-core-strings/

**Comment by DaVinci9196** [comment]
> Translations are now on weblate https://hosted.weblate.org/projects/microg/play-services-location-core-strings/

Do I need to translate my submission on this website?

**Comment by DaVinci9196** [comment]
> Translations are now on weblate https://hosted.weblate.org/projects/microg/play-services-location-core-strings/

I don't see this part of the string I translated on this website

**Comment by ygorigor** [comment]
> > Translations are now on weblate https://hosted.weblate.org/projects/microg/play-services-location-core-strings/
> 
> I don't see this part of the string I translated on this website

OK, then it's my mistake. Sory

**Review by mar-v-in — APPROVED** [review]

**Pull request merged**
