### PR TITLE
172yevwvsbwu

### PR DESCRIPTION
**Pull request by Sergo19911991**
vggggg

### CODE REVIEW

**Comment by Sergo19911991** [comment]
Uy

**Comment by Sergo19911991** [comment]
Hayward e

**Comment by Sergo19911991** [comment]
Huawei p40 lite

**Comment by ale5000-git** [comment]
I'm not sure if it is easy to do but the Google enforcement is only active for new ROMs, so instead of faking the device it is probably easier to fae the ROM date to something like 2017/2018.

**Comment by ale5000-git** [comment]
@Sergo19911991: microG GmsCore can now fake different device.

**Pull request closed without merging**
