### PR TITLE
Added Vending IntegrityService

### PR DESCRIPTION
**Pull request by DaVinci9196**
TotalPass <com.totalpassmobile> :  The ExpressIntegrityService service test passed.
Easypark <net.easypark.android> :  The IntegrityService service test passed.

### CODE REVIEW

**Comment by lucasmz-dev** [comment]
Does this supersede #2077?

**Comment by tgm-git** [comment]
Are there any plans for merging this PR soon?

**Comment by fynngodau** [comment]
@tgm-git As you can see from the sidebar, this PR is milestoned for 0.3.6 at this moment.

**Comment by michael1900** [comment]
> @tgm-git As you can see from the sidebar, this PR is milestoned for 0.3.6 at this moment.

Why not before? 
With this PI finally will work app like **ebay**, **macdonald** and **chatgpt**?

**Comment by BurhanBudak** [comment]
> > @tgm-git As you can see from the sidebar, this PR is milestoned for 0.3.6 at this moment.
> 
> Why not before? With this finally will work app like **ebay**, **macdonald** and **chatgpt**?

with latest news of Google doubling down on PI, maybe but the issue is the abusive use of the API by some apps. JohnW did say that it is over used for useless things.

**Pull request merged**
