### PR TITLE
View recent SafetyNet requests

### PR DESCRIPTION
**Pull request by iTrooz**
As discussed in #1738, this PR adds a new tab to view the recent SafetyNet requests made by applications
A few things to note :
- This is my first time working on an Android project, so while I tried my best, there might be some beginner mistakes (Please do not hesitate to tell me how I could improve my code !)
- I won't be available until a few days to fix things you report to me. I still wanted to open the PR now so you can do a review whenever you want

### CODE REVIEW

**Comment by ale5000-git** [comment]
@iTrooz
The build failed, could you please check? https://github.com/microg/GmsCore/runs/7953555572?check_suite_focus=true

**Comment by iTrooz** [comment]
I'll do it as soon as I can (in 2-3 days)

**Comment by iTrooz** [comment]
Done !

**Comment by mar-v-in** [comment]
Merged via 8c9aacee54b313aa4647be844117c583cbcec8c2. Thanks :)

**Pull request closed without merging**
